name: local_transform
channels:
  - conda-forge
  - pytorch
  - nvidia
  - dglteam
dependencies:
  - pip:
      - dgllife
  - conda-forge::python=3.6
  - conda-forge::pip
  - conda-forge::rdkit
  - nvidia::cudatoolkit=11.3
  - pytorch::pytorch
  - dglteam::dgl-cuda11.3
